GET https://fierce-headland-66218.herokuapp.com/api/v1/flower

###
POST https://fierce-headland-66218.herokuapp.com/api/v1/flower
Content-Type: application/json

{
  "sepalLength": 889.0,
  "color": "red",
  "price": 454.0
}